name: "Push Docker image to ghcr.io"

on:
  release:
    types:
      - released

jobs:
  docker:
    runs-on: ubuntu-22.04
    permissions:
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Login"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: "Push"
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kerka:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository_owner }}/kerka:latest
